### ISSUE TITLE
Cryptic segmentation fault error

### ISSUE THREAD

**Issue by jnesme** [smaegol/PlasFlow#13]
Hi and thanks for the work done.

I was running PlasFlow on a pretty big metagenomic assembly. I've only retained contigs above 1kb but I'm still left with half a million contigs. PlasFlow was running smoothly until the prediction step using for 7-mer (see console output below )

Beside that specific dataset PlasFlow runs great on smaller datasets so it doesn't seem to be an installation issue. I'm running it in a dedicated conda environement.

Is this due to a memory issue and is there anyway to resume the PlasFlow run from intermediary files ? ie not recounting all kmers etc, just doing the classfication setep maybe tweaking batch_size parameter? I'm running that on Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 and the server is pretty decent RAM wise with 1To installled for 64 cores...

Any ideas to process that dataset are welcome :)

Line run:
`PlasFlow.py --input ../anvio.megahit_kstep8.1Kbcontigs.fasta --output PlasFlow_out.megahit_kstep8.1kb`

```
...
processing chunk: 20
processing chunk: 21
processing chunk: 22
Transforming kmer frequencies
Finished transforming, saving transformed values
Predicting labels using kmer 6  frequencies
Calculating kmer frequencies using kmer 7
Due to large number of sequences in the input file, it is splitted to smaller chunks (maximum size: 25000 sequences)
processing chunk: 1
processing chunk: 2
processing chunk: 3
processing chunk: 4
processing chunk: 5
processing chunk: 6
processing chunk: 7
processing chunk: 8
processing chunk: 9
processing chunk: 10
processing chunk: 11
processing chunk: 12
processing chunk: 13
processing chunk: 14
processing chunk: 15
processing chunk: 16
processing chunk: 17
processing chunk: 18
processing chunk: 19
processing chunk: 20
processing chunk: 21
processing chunk: 22
Transforming kmer frequencies
Finished transforming, saving transformed values
Predicting labels using kmer 7  frequencies
Segmentation fault
```

**Comment by smaegol** [comment]
Hi, 

the issue is with the Biostrings R package, which have limitations on the amount of sequences processed at once. Sometimes it happens to produce an error for kmer 7 frequencies calculations. To circumvent this in the current release of PlasFlow there is an option `--batch-size` available, which can help with your problem.

First you have to remove all intermediate sequence chunks from the previous call:
`rm ../anvio.megahit_kstep8.1Kbcontigs.fasta_group*.fasta` 
and then try to set smaller values of `--batch-size` than the default one (25000 sequences per chunk). This should help.

For smaller kmers PlasFlow will resume from intermediate files which should be stored along input sequences (in your case as ../anvio.megahit_kstep8.1Kbcontigs.fasta_kmer_5_freqs.npy and ../anvio.megahit_kstep8.1Kbcontigs.fasta_kmer_6_freqs.npy).

**Comment by jnesme** [comment]
I think this is not directly related to the current issue but I'm running into that issue now after trying to reinstall conda and plasflow from scratch in a dedicated environment :/

```
Traceback (most recent call last):
  File "/usr/local/home/jnesme/miniconda2/envs/plasflow/bin/PlasFlow.py", line 50, in <module>
    from rpy2.robjects.packages import importr
  File "/usr/local/home/jnesme/miniconda2/envs/plasflow/lib/python3.5/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/usr/local/home/jnesme/miniconda2/envs/plasflow/lib/python3.5/site-packages/rpy2/rinterface/__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: /usr/local/home/jnesme/miniconda2/envs/plasflow/lib/python3.5/site-packages/rpy2/rinterface/_rinterface.cpython-35m-x86_64-linux-gnu.so: undefined symbol: Rf_installChar
```
