### ISSUE TITLE
Tensor name "dnn/hiddenlayer_0/biases" not found in checkpoint files

### ISSUE THREAD

**Issue by csawye01** [smaegol/PlasFlow#6]
Hello,

I had a few issues installing PlasFlow on my macOS Sierra but it now appears to have installed correctly with all the packages required. The error I am now having is:

NotFoundError (see above for traceback): Tensor name "dnn/hiddenlayer_0/biases" not found in checkpoint files 
./Documents/PlasFlow/models/kmer5_split_20_20_neurons_relu/model.ckpt-50000-?????-of-00001
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

I do not have an in depth understanding of TensorFlow to work out if this issue is caused by a fault in the file I have input or if it simply isn't compatible to run with OS X. 

Any help would be appreciated!

**Comment by smaegol** [comment]
Hi,

I suspect the problem lies in the TensorFlow installation. Unfortunately PlasFlow in the current version requires quite old version of TF, 0.10.RC3, which can be hard to install in the other way than conda. 
Have you tried installing tensorflow with pip: pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp35-cp35m-linux_x86_64.whl ? (please note that Python 3.5 is required!).

Unfortunately I haven't tested this software on Mac OS, but this will be fixed in the future release (networks are in the computation now).

best,
Pawel

**Comment by smaegol** [comment]
New version of PlasFlow supports MacOs. Please see the updated installation instructions.
